'use strict';/*
 lui.js web frame work 0.11.1
 inspired by react and mithril
 L3P3.de 2020
*/
{let d=null,f=!0,h=d,k=0,m=0,r=new Set,u=new Set,v=f,w=!f;
const y={},B={},D=d,E=f,F=w,G=Array,H=Object,I=H.assign,J=H.keys,aa=document,K=window,ba=K.performance||Date,ca=({f:{h:a}})=>a===L?"list":a.name_||a.name||"?",da=()=>{const a=[];let b=d,c=D;for(;b!==D;)a.unshift(ca(b)+(c!==D?":"+c:"")),c=b.j,b=b.i;return a.join(">")||"-"},M=a=>{throw Error("lui: "+a);},O=(a,b)=>{a===b||a!==D&&b!==D&&JSON.stringify(J(a))===JSON.stringify(J(b))||M("object keys mismatch")},P=(a,b)=>{h===D&&M("hook called outside of hook context");b&&d.l!==h&&M("hook called outside of component rendering");
a!==D&&k<h.length&&h[k][0]!==a&&M("inconsistent hook order at #"+k)},R=(a,b)=>{P(D,F);a!==Q(a,a)&&M(b+" changed between renderings")},ea=(a,b)=>(O(a,b),a===b?[]:J(a).filter(c=>a[c]!==b[c])),S=(a,b)=>(O(a,b),a!==b&&J(a).some(c=>a[c]!==b[c])),L=(a,b)=>{b!==D?(0===b.length&&M("deps empty"),a.length!==b.length&&M("deps length changed")):0<a.length&&M("deps presence changed");if(b!==D){let c=a.length;do if(a[--c]!==b[c])return F;while(0<c)}return E},T=(a,b)=>{const c=d,e=b;h=c.l;k=0;r.delete(c);if(c.f.h!==
L){var g=D;try{g=c.f.h(c.f.g)}catch(t){if(t!==y)throw t;}var l=c.a;"object"!==typeof g&&M("components need to return child list or null");if(g!==D){l!==D&&(a=l,b=D);var n=g.length,z;"number"!==typeof n&&M("childs must be returned in a list");0===n&&M("returned childs list empty");c.b!==D&&n!==c.b.length&&M("returned childs count changed");var C=c.b||(c.b=(new G(n)).fill(D));do{var p=C[--n];(z=g[n])&&z!==E?(p!==D&&p.f.h!==z.h&&M("child replaced at "+n),(f=p===D)?(C[n]=d=p={f:z,i:c,j:n,l:[],b:D,a:D,
c:D},T(a,b),p.a!==D&&a.insertBefore(p.c=p.a,b)):S(p.f.g,z.g)&&((d=p).f=z,T(a,b)),p.c!==D&&(b=p.c)):p!==D&&(U(p,a),C[n]=D)}while(0<n)}else if(c.b!==D){for(n of c.b)n!==D&&U(n,a);c.b=D}l===D&&(c.c=b!==e?b:D)}else{z=c.f.g.h;var q=c.f.g.G;g=c.f.g.g;l=V({s:D});"object"===typeof q&&q!==D&&"number"===typeof q.length||M("list_data must be an array");"object"!==typeof g&&M("props must be an object");R(z,"item component");R(g===D,"props presence");0<q.length&&(l.s!==D?(typeof q[0]!==l.s&&M("item type changed"),
"object"===typeof q[0]&&q[0]!==D&&typeof q[0].id!==l.H&&M("item id type changed")):(["object","string","number"].includes(l.s=typeof q[0])||M("item type invalid"),"object"===typeof q[0]&&q[0]!==D&&!["string","number"].includes(l.H=typeof q[0].id)&&M("item id type invalid")));l={};n=[];p=q.length;C=F;if(0<p){C="object"===typeof q[0];for(var A of q){A===D&&M("item is null");typeof A!==typeof q[0]&&M("item type changed");C&&typeof A.id!==typeof q[0].id&&M("item id type changed");var x=C?A.id:A;x in l&&
M("item not unique");l[x]=A;n.push(x)}}A=V();x=Q(n);q=g===D?D:Q(g);q=f||S(g,q);if(!f)for(var N of x)N in l||(U(A[N],a),delete A[N]);for(N=c.b=new G(p);0<p;){x=n[--p];let t=A[x];if(f=void 0===t)A[x]=d=t={f:{h:z,g:g===D?{I:l[x]}:I({I:l[x]},g)},i:c,j:p,l:[],b:D,a:D,c:D},T(a,b),t.a!==D&&a.insertBefore(t.c=t.a,b);else if(t.j!==p&&(fa(t,a,b),t.j=p),q||C&&S(l[x],t.f.g.I))(d=t).f.g=g===D?{I:l[x]}:I({I:l[x]},g),T(a,b);(N[p]=t).c!==D&&(b=t.c)}c.c=b!==e?b:D}},U=(a,b)=>{b!==D&&a.a!==D&&(b.removeChild(a.a),b=
D);if(a.b!==D)for(const c of a.b)c!==D&&U(c,b);for(const c of a.l)switch(c[0]){case 0:c[2]!==D&&c[2](c[1]);break;case 1:c[1]=D}r.delete(a);u.delete(a)},fa=(a,b,c)=>{if(a.a!==D)return b.insertBefore(a.a,c),a.a;if(a.c!==D){let e=a.b.length;do a.b[--e]!==D&&(c=fa(a.b[e],b,c));while(0<e)}return c},ha=()=>{P(D,E);u.add(d)},ia=(a,b)=>{P(0,F);if(k<h.length){const c=h[k++];L(c[1],b||D)||(c[2]!==D&&c[2](...c[1]),c[2]=a(...c[1]=b||[])||D)}else h[k++]=[0,b=b||[],a(...b)||D];h[k-1][2]&&h[k-1][2].then&&M("effect function must be synchronous, use hook_async instead")},
ja=a=>{P(2,E);if(k<h.length)return h[k++][1];const b=d,c=[a,e=>{c[0]!==e&&(c[0]=e,r.add(b),v||W())},()=>c[0]];h[k++]=[2,c];return c},V=a=>{P(3,F);return(k<h.length?h[k++]:h[k++]=[3,void 0===a?{}:a])[1]},ka=(a,b)=>{P(4,F);if(k<h.length){const c=h[k++];return L(c[1],b||D)?c[2]:c[2]=a(...c[1]=b||[])}a=a(...b=b||[]);h[k++]=[4,b,a];return a},Q=(a,b)=>{P(5,F);if(k<h.length){b=h[k++];const c=b[1];b[1]=a;return c}h[k++]=[5,a];return b},la=(a,b)=>{const c=setTimeout(()=>{b(E)},a);return()=>{clearTimeout(c)}},
X=a=>{const b=Q(a);return f?J(a):ea(b,a)},Y=a=>{R(a===D,"attributes presence");const b=d.a;if(a!==D){for(const c of X(a))switch(1<c.length&&c.charAt(0).toLowerCase()!==c.charAt(0)&&M("capital prop: "+c),c.charCodeAt(0)){case 70:a.F!==D&&"object"===typeof a.F||M("invalid css flags");b.className=J(a.F).filter(e=>a.F[e]).join(" ");continue;case 82:"function"!==typeof a.R&&M("invalid ref"),a.R(b);case 67:case 83:continue;default:97>c.charCodeAt(0)&&M("invalid prop: "+c),b[c]=a[c]}R(!a.S,"style presence");
if(a.S)for(const c of X(a.S))b.style[c]=a.S[c]}return b},Z=(a,b,c)=>("string"===typeof a&&M("component expected, use node_dom instead"),void 0!==c&&(!c||c.constructor!==G)&&M("invalid childs type"),{h:a,g:b?c?(b.C=c,b):b:c?{C:c}:D}),W=()=>{m=ba.now();v=E;for(d of r)if(f=F,d.a!==D)T(D,D);else{let a,b=D,c=d.c,e=d,g=d;for(;(a=(e=e.i).a)===D;);do{let l=g.j;const {b:n}=g=g.i,z=n.length;for(;++l<z&&(n[l]===D||(b=n[l].c)===D););}while(b===D&&g!==e);g=d;T(a,b);if(g.c!==c)for(;(g=g.i).a===D;){c=D;for(const l of g.b)if(l!==
D&&(c=l.c)!==D)break;if(c===g.c)break;g.c=c}}v=F;d=h=D;!w&&0<u.size&&(w=E,requestAnimationFrame(ma))},ma=()=>{w=F;const a=r;r=u;(u=a).clear();W()},na=a=>{var b=y[a];if(void 0===b){const c=a.indexOf("[");b=0>c?a.substr(0):a.substr(0,c);(0===b.length||b!==b.toLowerCase()||b.includes(" ")||b.includes("#")||b.includes("."))&&M("dom: invalid tag");y[a]=b=aa.createElement(b);if(0<c){!a.endsWith("]")&&M("dom: ] missing");for(const e of a.substring(c+1,a.length-1).split("]["))!e&&M("dom: empty attribute"),
(e.includes("[")||e.includes("]"))&&M("dom: attributes screwed up"),a=e.indexOf("="),e.includes(" ")&&(0>a||e.indexOf(" ")<a)&&M("dom: space in attribute name"),0<a?b[e.substr(0,a)]=e.substr(a+1):b[e]=E}}return b},oa=a=>{let b=B[a];if(void 0===b){const c=na(a);B[a]=b=e=>(f&&(d.a=c.cloneNode(E)),Y(e),e!==D&&e.C||D);b.name_="$"+a}return b};K.onerror=()=>{d!==D&&console.log("lui "+da()+": error",...[]);return r.clear(),u.clear()};K.lui={hook_assert:a=>{P(D,F);if(!a)throw y;},hook_async:(a,b,c)=>{P(1,E);const e=k<h.length?h[k++]:h[k++]=[1,D,D];if(e[1]!==D&&L(e[1],b||D))return e[2];void 0!==c&&(e[2]=c);const g=d;a(...e[1]=b=b||[]).then(l=>{e[2]!==l&&e[1]===b&&(e[2]=l,r.add(g),v||W())});return e[2]},hook_callback:(a,b)=>{const c=V();c.D=b;f&&(c.B=(...e)=>a(...c.D,...e));return c.B},hook_delay:a=>{const [b,c]=ja(F);ia(la,[a,c]);return b},hook_dom:(a,b)=>(P(D,E),d.a===D?f||M("hook_dom skipped before"):f&&M("hook_dom called twice"),
void 0!==b&&(void 0!==b.C&&M("hook_dom cannot have childs"),void 0!==b.R&&M("hook_dom cannot have a ref")),f&&(d.a=na(a).cloneNode(E)),Y(b||D)),hook_effect:ia,hook_first:()=>(P(D,F),f),hook_memo:ka,hook_object_changes:X,hook_prev:Q,hook_reducer:a=>{P(6,E);"function"===typeof a&&M("array required, use hook_reducer_f instead");if(k<h.length)return h[k++][1];const b=d,c=[a[0](),(e,g)=>{e=a[e](c[0],g);c[0]!==e&&(c[0]=e,r.add(b),v||W())}];h[k++]=[6,c];return c},hook_reducer_f:(a,b)=>{P(7,E);"function"!==
typeof a&&M("function required");if(k<h.length)return h[k++][1];const c=d,e=[b?b():D,g=>{g=a(e[0],g);e[0]!==g&&(e[0]=g,r.add(c),v||W())}];h[k++]=[7,e];return e},hook_rerender:ha,hook_state:ja,hook_static:V,hook_sub:(a,b)=>{P(8,F);let c=D;if(k++<h.length)if((c=h[k-1])[1]!==a)c=D;else if(L(c[2],b||D))return c[3];const e=f,g=h,l=k;b=b||[];(f=c===D)?h[k-1]=c=[8,a,b,D,[]]:c[2]=b;h=c[4];k=0;try{c[3]=a(...b)}catch(n){if(n!==y)throw n;}f=e;h=g;k=l;return c[3]},hook_transition:(a,b)=>{const c=V({m:a});a=ka((e,
g)=>({u:c.m,A:e,o:m,v:f?m:m+g}),[a,b]);if(a.v<=m)return c.m=a.A;ha();return c.m=a.o===m?a.u:a.u+(a.A-a.u)*(m-a.o)/(a.v-a.o)},init:a=>{(d!==D||0<r.size)&&M("init called more than once");"function"!==typeof a&&M("init function requires body component");let b;const c=aa.body;c.innerHTML="";const e=()=>((!(b=a())||2!==b.length)&&M("root component must return [props, childs]"),R(b[0]===D,"attributes presence"),b[0]!==D&&("object"!==typeof b[0]&&M("invalid props type"),O(Q(b[0],b[0]),b[0]),void 0!==b[0].C&&
M("body childs must be in second return value")),Y(b[0]),b[1]);e.name_="$body";d={f:{h:e,g:D},i:D,j:0,l:[],b:D,a:c,c};m=ba.now();T(D,D);W()},node:Z,node_dom:(a,b,c)=>Z(oa(a),b,c),node_map:(a,b,c)=>Z(L,{h:a,G:b,g:c||D}),now:()=>m}}